package org.nishgrid.clienterp.controller;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.datatype.jsr310.JavaTimeModule;
import javafx.application.Platform;
import javafx.collections.FXCollections;
import javafx.fxml.FXML;
import javafx.scene.control.*;
import javafx.util.StringConverter;
import org.nishgrid.clienterp.dto.CustomerDTO;
import org.nishgrid.clienterp.dto.GiftVoucherCreateDTO;
import org.nishgrid.clienterp.dto.GiftVoucherResponseDTO;
import org.nishgrid.clienterp.dto.VoucherStatusUpdateDTO;
import org.nishgrid.clienterp.model.GiftVoucher;
import org.nishgrid.clienterp.service.ApiService;

import java.math.BigDecimal;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.util.List;
import java.util.Objects;
import java.util.stream.Collectors;

public class GiftVoucherController {

    @FXML private TextField voucherCodeField, valueField;
    @FXML private ComboBox<CustomerDTO> customerComboBox;
    @FXML private ComboBox<String> statusBox;
    @FXML private TableView<GiftVoucher> voucherTable;
    @FXML private TableColumn<GiftVoucher, String> voucherCodeCol;
    @FXML private TableColumn<GiftVoucher, String> customerNameCol;
    @FXML private TableColumn<GiftVoucher, Number> valueCol;
    @FXML private TableColumn<GiftVoucher, String> statusCol;

    private final HttpClient httpClient = HttpClient.newHttpClient();
    private final ObjectMapper objectMapper = new ObjectMapper().registerModule(new JavaTimeModule());
    private final String API_BASE_URL = ApiService.getBaseUrl() + "/vouchers";

    @FXML
    public void initialize() {
        statusBox.setItems(FXCollections.observableArrayList("USED", "UNUSED"));
        voucherCodeField.setEditable(false);
        voucherCodeField.setPromptText("Auto-generated by server");

        voucherCodeCol.setCellValueFactory(data -> data.getValue().voucherCodeProperty());
        customerNameCol.setCellValueFactory(data -> data.getValue().customerNameProperty());
        valueCol.setCellValueFactory(data -> data.getValue().valueProperty());
        statusCol.setCellValueFactory(data -> data.getValue().statusProperty());

        voucherTable.getSelectionModel().selectedItemProperty().addListener(
                (obs, old, newVoucher) -> { if (newVoucher != null) populateForm(newVoucher); });

        configureComboBoxes();
        loadCustomers();
        loadVouchers();
    }

    private void configureComboBoxes() {
        customerComboBox.setConverter(new StringConverter<>() {
            @Override public String toString(CustomerDTO c) { return c == null ? null : c.getName(); }
            @Override public CustomerDTO fromString(String s) { return null; }
        });
    }

    private void loadCustomers() {
        String url = ApiService.getBaseUrl() + "/customers/selection";
        HttpRequest request = HttpRequest.newBuilder().uri(URI.create(url)).GET().build();
        httpClient.sendAsync(request, HttpResponse.BodyHandlers.ofString())
                .thenApply(HttpResponse::body)
                .thenAccept(body -> {
                    try {
                        List<CustomerDTO> customers = objectMapper.readValue(body, new TypeReference<>() {});
                        Platform.runLater(() -> customerComboBox.setItems(FXCollections.observableArrayList(customers)));
                    } catch (Exception e) { e.printStackTrace(); }
                });
    }

    private void loadVouchers() {
        HttpRequest request = HttpRequest.newBuilder().uri(URI.create(API_BASE_URL)).GET().build();
        httpClient.sendAsync(request, HttpResponse.BodyHandlers.ofString())
                .thenApply(HttpResponse::body)
                .thenAccept(body -> {
                    try {
                        List<GiftVoucherResponseDTO> dtoList = objectMapper.readValue(body, new TypeReference<>() {});
                        List<GiftVoucher> fxList = dtoList.stream()
                                .map(dto -> new GiftVoucher(
                                        dto.getId(),
                                        dto.getVoucherCode(),
                                        dto.getCustomerName(),
                                        dto.getValue(),
                                        dto.getStatus().toString()))
                                .collect(Collectors.toList());
                        Platform.runLater(() -> {
                            voucherTable.setItems(FXCollections.observableArrayList(fxList));
                            clearForm();
                        });
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                });
    }

    @FXML
    private void handleAdd() {
        CustomerDTO selectedCustomer = customerComboBox.getSelectionModel().getSelectedItem();
        if (selectedCustomer == null) {
            showAlert("Error", "Please select a customer.");
            return;
        }
        try {
            GiftVoucherCreateDTO createDto = new GiftVoucherCreateDTO();
            createDto.setCustomerId(selectedCustomer.getId());
            createDto.setValue(new BigDecimal(valueField.getText()));

            String requestBody = objectMapper.writeValueAsString(createDto);
            HttpRequest request = HttpRequest.newBuilder()
                    .uri(URI.create(API_BASE_URL))
                    .header("Content-Type", "application/json")
                    .POST(HttpRequest.BodyPublishers.ofString(requestBody))
                    .build();
            sendRequestAndRefresh(request, "Voucher added successfully!");
        } catch (NumberFormatException e) {
            showAlert("Error", "Please enter a valid number for the Value field.");
        } catch (Exception e) {
            showAlert("Error", "Failed to add voucher: " + e.getMessage());
        }
    }

    @FXML
    private void handleEdit() {
        GiftVoucher selected = voucherTable.getSelectionModel().getSelectedItem();
        if (selected == null) {
            showAlert("Warning", "Please select a voucher to update.");
            return;
        }
        String newStatus = statusBox.getValue();
        if (newStatus == null || newStatus.isBlank()) {
            showAlert("Warning", "Please select a new status.");
            return;
        }
        try {
            VoucherStatusUpdateDTO statusUpdateDTO = new VoucherStatusUpdateDTO();
            statusUpdateDTO.setStatus(newStatus);
            String requestBody = objectMapper.writeValueAsString(statusUpdateDTO);

            HttpRequest request = HttpRequest.newBuilder()
                    .uri(URI.create(API_BASE_URL + "/" + selected.getId() + "/status"))
                    .header("Content-Type", "application/json")
                    .PUT(HttpRequest.BodyPublishers.ofString(requestBody))
                    .build();
            httpClient.sendAsync(request, HttpResponse.BodyHandlers.ofString())
                    .thenAccept(response -> Platform.runLater(() -> {
                        if (response.statusCode() >= 200 && response.statusCode() < 300) {
                            showAlert("Success", "Voucher status updated!");
                            loadVouchers();
                        } else {
                            showAlert("Error", response.body());
                        }
                    }));
        } catch (Exception e) {
            showAlert("Error", "Failed to update voucher: " + e.getMessage());
        }
    }

    @FXML
    private void handleDelete() {
        GiftVoucher selected = voucherTable.getSelectionModel().getSelectedItem();
        if (selected == null) {
            showAlert("Warning", "Please select a voucher to delete.");
            return;
        }
        Alert confirmation = new Alert(Alert.AlertType.CONFIRMATION, "Delete voucher " + selected.getVoucherCode() + "?", ButtonType.YES, ButtonType.NO);
        if (confirmation.showAndWait().orElse(ButtonType.NO) == ButtonType.YES) {
            HttpRequest request = HttpRequest.newBuilder()
                    .uri(URI.create(API_BASE_URL + "/" + selected.getId()))
                    .DELETE().build();
            sendRequestAndRefresh(request, "Voucher deleted successfully!");
        }
    }

    private void sendRequestAndRefresh(HttpRequest request, String successMessage) {
        httpClient.sendAsync(request, HttpResponse.BodyHandlers.ofString())
                .thenAccept(response -> Platform.runLater(() -> {
                    if (response.statusCode() >= 200 && response.statusCode() < 300) {
                        showAlert("Success", successMessage);
                        loadVouchers();
                    } else {
                        showAlert("Error", response.body());
                    }
                }));
    }

    private void populateForm(GiftVoucher voucher) {
        voucherCodeField.setText(voucher.getVoucherCode());
        statusBox.setValue(voucher.statusProperty().get());

        BigDecimal value = (BigDecimal) voucher.valueProperty().getValue();
        if (value != null) {
            valueField.setText(value.toPlainString());
        } else {
            valueField.clear();
        }

        customerComboBox.getItems().stream()
                .filter(c -> Objects.equals(c.getName(), voucher.getCustomerName()))
                .findFirst()
                .ifPresent(customerComboBox.getSelectionModel()::select);
    }

    private void clearForm() {
        voucherTable.getSelectionModel().clearSelection();
        voucherCodeField.clear();
        customerComboBox.getSelectionModel().clearSelection();
        valueField.clear();
        statusBox.getSelectionModel().clearSelection();
    }

    private void showAlert(String title, String msg) {
        Alert.AlertType type = title.equals("Success") ? Alert.AlertType.INFORMATION : Alert.AlertType.WARNING;
        if (title.equals("Error")) type = Alert.AlertType.ERROR;
        Alert alert = new Alert(type, msg);
        alert.setTitle(title);
        alert.setHeaderText(null);
        alert.setContentText(msg);
        alert.showAndWait();
    }
}
