package org.nishgrid.clienterp.dto;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import lombok.Data;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.List;
import java.util.Optional;

@Data
@JsonIgnoreProperties(ignoreUnknown = true)
public class SalesInvoiceDto {
    private Long invoiceId;
    private String invoiceNo;
    private LocalDate invoiceDate;
    private String paymentMode;
    private BigDecimal totalAmount;
    private BigDecimal discount;
    private BigDecimal gstPercent;
    private BigDecimal netAmount;
    private String status;
    private String remarks;
    private BigDecimal oldGoldValue;
    private BigDecimal paidAmount;
    private BigDecimal dueAmount;
    private CustomerDTO customer;
    private List<SalesItemDto> salesItems;

    // The getter for dueAmount is automatically generated by Lombok's @Data annotation.
    // So, an explicit method is not required unless you need custom logic.
    // If you need to calculate it on the fly, you can add this method:
    public BigDecimal getDueAmount() {
        return Optional.ofNullable(getNetAmount()).orElse(BigDecimal.ZERO)
                .subtract(Optional.ofNullable(getOldGoldValue()).orElse(BigDecimal.ZERO))
                .subtract(Optional.ofNullable(getPaidAmount()).orElse(BigDecimal.ZERO));
    }
}